### PR TITLE
Added support for halfop and dehalfop and added # of users in a channel

### PR DESCRIPTION
**Pull request by paytonq**
I saw that issue #87 was requesting halfop support, so I implemented it. I tested the implementation on a Nexus 5 Emulator running 5.0.1 on Mibbit IRC.

Also implemented issue #33, which was very straightforward (Listing the number of users in a channel).

Edit: Note, some of the new translations may be somewhat off.

### CODE REVIEW

**Comment by indrora** [comment]
Some nits about style; don't commit the IDEA files (I know i need to add them to .gitignore).

As well, the "standard" (if you can call it a standard) is that halfops get `%` as a prefix.

**Comment by paytonq** [comment]
Should I revert the idea files?

**Comment by indrora** [comment]
See the comments; there's some issues with this commit overall.

**Comment by indrora** [comment]
Revert the IDEA files, and make sure that the translations make their way to Crowdin.

**Comment by paytonq** [comment]
Right, and switch halfops to %.  Working on it right now

**Comment by indrora** [comment]
Awesome :beers:

**Comment by paytonq** [comment]
Haven't used Crowdin before, what exactly do I do?

**Comment by paytonq** [comment]
Also, when I added halfop and dehalfop I fixed a bug that was causing the ban and kick functionalities to be reversed.

**Comment by indrora** [comment]
Awesome beans, looks like all is right with the world.

**Comment by paytonq** [comment]
Do you still need me to add the translations to Crowdin?

**Comment by indrora** [comment]
It'd be really nice to see them migrated up right now, but I can add them when I do a sync with Crowdin.

I'll have to add the English versions (as source lines) within Crowdin, but I'll be able to update the translations at the same time.

**Comment by paytonq** [comment]
Ok, thanks.

**Pull request merged**
